// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fitprint/models/achievement.dart';
import 'package:fitprint/models/body_metrics.dart';
import 'package:fitprint/models/day_log.dart';
import 'package:fitprint/models/exercise.dart';
import 'package:fitprint/models/run_log.dart';
import 'package:fitprint/models/sleep_log.dart';
import 'package:fitprint/models/user_profile.dart';
import 'package:fitprint/models/weight_entry.dart';
import 'package:fitprint/models/workout_routine.dart';
import 'package:fitprint/models/workout_session.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(BodyMetricsAdapter());
    registerAdapter(DayLogAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseHistoryEntryAdapter());
    registerAdapter(RunLogAdapter());
    registerAdapter(SleepLogAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutRoutineAdapter());
    registerAdapter(WorkoutSessionAdapter());
    registerAdapter(WorkoutSetAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(BodyMetricsAdapter());
    registerAdapter(DayLogAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseHistoryEntryAdapter());
    registerAdapter(RunLogAdapter());
    registerAdapter(SleepLogAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutRoutineAdapter());
    registerAdapter(WorkoutSessionAdapter());
    registerAdapter(WorkoutSetAdapter());
  }
}
