// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gym_tracker/models/body_metrics.dart';
import 'package:gym_tracker/models/day_log.dart';
import 'package:gym_tracker/models/exercise.dart';
import 'package:gym_tracker/models/run_log.dart';
import 'package:gym_tracker/models/user_profile.dart';
import 'package:gym_tracker/models/weight_entry.dart';
import 'package:gym_tracker/models/workout_routine.dart';
import 'package:gym_tracker/models/workout_session.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(BodyMetricsAdapter());
    registerAdapter(DayLogAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(RunLogAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutRoutineAdapter());
    registerAdapter(WorkoutSessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(BodyMetricsAdapter());
    registerAdapter(DayLogAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(RunLogAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutRoutineAdapter());
    registerAdapter(WorkoutSessionAdapter());
  }
}
